title: Daniel Furman 
logo: "/images/logo.png?raw=true" 
description: > 
  My name is Daniel, and I am a recent UPenn graduate with an interest in Data Science. 
  <br><br>
  <a target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/in/daniel-furman-702b02160/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
